export const vehicle_types = {
  0: "Car",
  1: "Truck",
  2: "Motorcycle",
  3: "Bus",
  4: "Van",
};

export const vehicle_list = [
  {
    id: 1,
    plate: "ABC123",
    mark: "Toyota",
    model: "Corolla",
    year: 2020,
    color: "Red",
    type: 0,
  },
  {
    id: 2,
    plate: "XYZ456",
    mark: "Ford",
    model: "F-150",
    year: 2019,
    color: "Blue",
    type: 1,
  },
  {
    id: 3,
    plate: "LMN789",
    mark: "Harley-Davidson",
    model: "Street 750",
    year: 2021,
    color: "Black",
    type: 2,
  },
  {
    id: 4,
    plate: "QRS012",
    mark: "Mercedes-Benz",
    model: "Sprinter",
    year: 2018,
    color: "White",
    type: 3,
  },
  {
    id: 5,
    plate: "TUV345",
    mark: "Honda",
    model: "Odyssey",
    year: 2022,
    color: "Silver",
    type: 4,
  },
  {
    id: 6,
    plate: "WXY678",
    mark: "Chevrolet",
    model: "Silverado",
    year: 2020,
    color: "Green",
    type: 1,
  },
];
